Update solutionsLib.py
Esri/mdcs-py pull request #113
Opened 2022-10-26 07:26 UTC by bikesbade

#110

2022-10-26 08:00 UTC, Chamlika commented on scripts/solutionsLib.py
> +                    self.modifyConfProperties(os.path.join(cachepath, 'conf.properties'), maxScale)
@bikesbade  Put the whole block in a try:  exception block to trap any errors in (returnLevelDetails, modifyConfProperties) functions. I see the XMLs loaded & modified without any error checks within the functions. Please return False if an exception is thrown with an appropriate error message logged to signal w/f failures. Thanks!

2022-10-26 08:01 UTC, Chamlika requested changes
Please read the comment, thanks! @bikesbade

2022-10-26 08:24 UTC, bikesbade commented
@Chamlika made the changes as requested. Thanks

2022-10-26 10:54 UTC, vijaygit02 approved these changes

2022-10-26 10:55 UTC, merged

2022-10-26 21:56 UTC, chritomix commented
Hi, with @bikesbade. I just have downloaded the latest script and it is not working. With your last update of module solutionsLib.py, you made a mistake with indentation. you must move "def modifyConfProperties(self, properties, maxScale)" function to the left. OTHERWISE THE MDSC is failing. thanks, Tomasz

2022-10-27 07:06 UTC, bikesbade commented
@chritomix  Thanks for pointing it out. Made the fixed. you can test it out. Thanks