[Deep Learning commands] Update solutionsLib.py
Esri/mdcs-py pull request #126
Opened 2023-06-01 16:56 UTC by surabhijain123

Issue: https://github.com/Esri/mdcs-py/issues/127

1. Adding Deep Learning Commands in MDCS
- CPUDL: ClassifyPixelsUsingDeepLearning
- DOUDL: DetectObjectsUsingDeepLearning
- COUDL: ClassifyObjectsUsingDeepLearning
- EFUAIM: Extract Features Using AI Models

2. Fix in Set Environment in case input is '#'

2023-06-01 17:05 UTC, surabhijain123 commented
@Chamlika Please review this

2023-06-02 04:06 UTC, Chamlika commented
@abhiataero This was approved earlier.

2023-06-02 04:12 UTC, Chamlika commented
@surabhijain123 The changes that were added earlier aren't reflected here in the source here. It's possible the PR isn't attached to this particular issue #, can you check, thanks!

2023-06-02 04:29 UTC, Chamlika requested changes
Looks like the changes that you'd done earlier on the PR aren't automatically reflected in the source here. I'd added the requested comments once again, thanks!

2023-06-02 04:29 UTC, Chamlika commented on scripts/solutionsLib.py
> +
Please remove empty line, thanks!

2023-06-02 04:29 UTC, Chamlika commented on scripts/solutionsLib.py
> +                    os.path.join(self.m_base.m_geoPath, self.m_base.m_mdName + processKey),
Use the variable {fullPath} here

2023-06-02 04:29 UTC, Chamlika commented on scripts/solutionsLib.py
> +                out_classified_raster.save(os.path.join(self.m_base.m_geoPath, self.m_base.m_mdName + processKey))
out_classified_raster.save(f’{fullPath}{processKey}’)

2023-06-02 04:55 UTC, Chamlika commented
@surabhijain123 This was the earlier PR they'd worked on that have the same code changes and that was approved. Not sure why you'd have multiple issues though on the same changes, perhaps you could discard this issue.

https://github.com/ArcGIS/AID/pull/6829

2023-06-05 07:47 UTC, surabhijain123 commented on scripts/solutionsLib.py
> +
Done

2023-06-05 07:48 UTC, surabhijain123 commented on scripts/solutionsLib.py
> +                    os.path.join(self.m_base.m_geoPath, self.m_base.m_mdName + processKey),
Done

2023-06-05 07:49 UTC, surabhijain123 commented on scripts/solutionsLib.py
> +                out_classified_raster.save(os.path.join(self.m_base.m_geoPath, self.m_base.m_mdName + processKey))
Done

2023-07-27 08:49 UTC, merged